In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("Customer-Churn.csv")

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.Churn.value_counts()/len(df) * 100

Churn
No     73.463013
Yes    26.536987
Name: count, dtype: float64

### **Churn Rate 26.53 %**

which means 26.53% of the customers are churn out of this telecom industry.

In [6]:
## Divide data into X and y - X (Independent features), y(Dependent variable)

# Define y (target variable)
y = df['Churn']

# Define X (features) by dropping 'customerID' and 'Churn'
X = df.drop(columns=['customerID', 'Churn'])

# Optional: Verify the shapes
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (7043, 19)
Shape of y: (7043,)

## Train Test Split

In [7]:
X = pd.get_dummies(X, drop_first=True)
y = df['Churn'].map({'No': 0, 'Yes': 1})

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Model Building

In [9]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [10]:
y_pred_dt = model_dt.predict(X_test)

In [11]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.83      0.86      0.85      1033
           1       0.58      0.51      0.54       376

    accuracy                           0.77      1409
   macro avg       0.70      0.68      0.69      1409
weighted avg       0.76      0.77      0.76      1409

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

## Initial Insights

- Base model has a accuracy of 76% which is not reliable because of the imbalanced dataset
- TotalCharges needs to be a float/int type (Data Cleaning)
- Need to perform Feature Scaling

## Data Cleaning

In [13]:
telco_data = df.copy()

In [14]:
telco_data.TotalCharges = pd.to_numeric(telco_data.TotalCharges, errors='coerce')

In [16]:
telco_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [17]:
telco_data.loc[telco_data['TotalCharges'].isnull() == True]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [18]:
telco_data.dropna(how='any', inplace=True)

In [19]:
telco_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [20]:
telco_data.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [21]:
telco_data.tenure.max()

72

In [22]:
import pandas as pd

# Define the bin edges (0 to 72, stepping by 12 months)
bins = [0, 12, 24, 36, 48, 60, 72]

# Define the labels for each bin
labels = ['1-12', '13-24', '25-36', '37-48', '49-60', '61-72']

# Create the new binned column
telco_data['tenure_bin'] = pd.cut(telco_data['tenure'], bins=bins, labels=labels, include_lowest=True)

# Optional: Check the result
print(telco_data[['tenure', 'tenure_bin']].head(10))
print(telco_data['tenure_bin'].value_counts().sort_index())

   tenure tenure_bin
0       1       1-12
1      34      25-36
2       2       1-12
3      45      37-48
4       2       1-12
5       8       1-12
6      22      13-24
7      10       1-12
8      28      25-36
9      62      61-72
tenure_bin
1-12     2175
13-24    1024
25-36     832
37-48     762
49-60     832
61-72    1407
Name: count, dtype: int64

In [23]:
telco_data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_bin
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1-12
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,25-36
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1-12
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,37-48
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1-12

In [24]:
## Divide data into X and y - X (Independent features), y(Dependent variable)

# Define y (target variable)
y = telco_data['Churn']

# Define X (features) by dropping 'customerID' and 'Churn'
X = telco_data.drop(columns=['customerID', 'Churn', 'tenure'])

# Optional: Verify the shapes
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (7032, 19)
Shape of y: (7032,)

In [26]:
X.head()

,gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,tenure_bin
0,Female,0,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,1-12
1,Male,0,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,25-36
2,Male,0,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1-12
3,Male,0,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,37-48
4,Female,0,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1-12

In [27]:
X = pd.get_dummies(X, drop_first=True)
y = telco_data['Churn'].map({'No': 0, 'Yes': 1})

In [28]:
X.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,...,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_bin_13-24,tenure_bin_25-36,tenure_bin_37-48,tenure_bin_49-60,tenure_bin_61-72
0,0,29.85,29.85,False,True,False,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
1,0,56.95,1889.50,True,False,False,True,False,False,False,...,False,False,False,False,True,False,True,False,False,False
2,0,53.85,108.15,True,False,False,True,False,False,False,...,False,True,False,False,True,False,False,False,False,False
3,0,42.30,1840.75,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,False,False,False,True,False,False,True,...,False,True,False,True,False,False,False,False,False,False

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Feature Scaling

In [30]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [31]:
model_dt2 = DecisionTreeClassifier()
model_dt2.fit(X_train, y_train)

y_pred_dt2 = model_dt2.predict(X_test)

In [32]:
print(classification_report(y_test, y_pred_dt2))

              precision    recall  f1-score   support

           0       0.81      0.82      0.82      1030
           1       0.49      0.47      0.48       377

    accuracy                           0.73      1407
   macro avg       0.65      0.65      0.65      1407
weighted avg       0.72      0.73      0.73      1407

## Feature Scaling - MinMaxScaler

In [34]:
from sklearn.preprocessing import MinMaxScaler

In [35]:
mms = MinMaxScaler()
X_train_mms = mms.fit_transform(X_train)
X_test_mms = mms.transform(X_test)

In [36]:
model_dt3 = DecisionTreeClassifier()
model_dt3.fit(X_train_mms, y_train)

y_pred_dt3 = model_dt3.predict(X_test_mms)

In [37]:
print(classification_report(y_test, y_pred_dt3))

              precision    recall  f1-score   support

           0       0.81      0.83      0.82      1030
           1       0.49      0.45      0.47       377

    accuracy                           0.73      1407
   macro avg       0.65      0.64      0.65      1407
weighted avg       0.72      0.73      0.73      1407

## SMOTEENN () [UpSampling + ENN)

🔁 1. SMOTE (UpSampling)

SMOTE = Synthetic Minority Over-sampling Technique

It creates new synthetic samples for the minority class (instead of just duplicating existing ones).
It works by interpolating between nearby minority samples.

👉 Result: The minority class gets more data points → better balance.2. ENN (Edited Nearest Neighbors)

ENN = a cleaning method (UnderSampling)

It removes samples (usually from the majority class) that are:
Misclassified by their nearest neighbors
Noisy or ambiguous

👉 Result: The dataset becomes cleaner and less noisy

In [40]:
from imblearn.combine import SMOTEENN

In [41]:
sm = SMOTEENN()
X_train_resampled, y_train_resampled = sm.fit_resample(X_train, y_train)

In [42]:
model_dt_smoteenn = DecisionTreeClassifier()
model_dt_smoteenn.fit(X_train_resampled, y_train_resampled)

y_pred_dt_smoteenn = model_dt_smoteenn.predict(X_test)

In [43]:
print(classification_report(y_test, y_pred_dt_smoteenn))

              precision    recall  f1-score   support

           0       0.88      0.70      0.78      1030
           1       0.47      0.75      0.58       377

    accuracy                           0.71      1407
   macro avg       0.68      0.72      0.68      1407
weighted avg       0.77      0.71      0.72      1407

In [44]:
model_rf_smoteenn = RandomForestClassifier(n_estimators=500)
model_rf_smoteenn.fit(X_train_resampled, y_train_resampled)

y_pred_rf_smoteenn = model_rf_smoteenn.predict(X_test)

In [45]:
print(classification_report(y_test, y_pred_rf_smoteenn))

              precision    recall  f1-score   support

           0       0.91      0.70      0.79      1030
           1       0.50      0.81      0.62       377

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.80      0.73      0.74      1407

## XGBoost without SMOTEENN

In [ ]:
from xgboost import XGBClassifier

# Initialize and train the XGBoost model
model_xgb = XGBClassifier(random_state=42)  # random_state for reproducibility
model_xgb.fit(X_train, y_train)

# Make predictions on the test set
y_pred_xgb = model_xgb.predict(X_test)

In [47]:
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85      1030
           1       0.58      0.47      0.52       377

    accuracy                           0.77      1407
   macro avg       0.70      0.67      0.68      1407
weighted avg       0.76      0.77      0.76      1407

## XGBoost with SMOTEENN

In [48]:
from xgboost import XGBClassifier

# Initialize and train the XGBoost model
model_xgb_smoteenn = XGBClassifier(random_state=42)  # random_state for reproducibility
model_xgb_smoteenn.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred_xgb_smoteenn = model_xgb_smoteenn.predict(X_test)

In [49]:
print(classification_report(y_test, y_pred_xgb_smoteenn))

              precision    recall  f1-score   support

           0       0.90      0.70      0.79      1030
           1       0.49      0.79      0.61       377

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.74      1407

## XGBoost with SMOTE

In [50]:
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from collections import Counter

# Check class distribution before SMOTE
print("Before SMOTE:", Counter(y_train))

# Apply SMOTE to the training data only
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# Check class distribution after SMOTE
print("After SMOTE:", Counter(y_train_smote))

# Initialize and train the XGBoost model on resampled data
model_xgb_smote = XGBClassifier(random_state=42)
model_xgb_smote.fit(X_train_smote, y_train_smote)

# Make predictions on the original test set (unchanged)
y_pred_xgb_smote = model_xgb_smote.predict(X_test)

Before SMOTE: Counter({0: 4133, 1: 1492})
After SMOTE: Counter({0: 4133, 1: 4133})

In [51]:
print(classification_report(y_test, y_pred_xgb_smote))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85      1030
           1       0.59      0.57      0.58       377

    accuracy                           0.78      1407
   macro avg       0.72      0.71      0.72      1407
weighted avg       0.78      0.78      0.78      1407

In [52]:
from imblearn.over_sampling import ADASYN
from xgboost import XGBClassifier
from collections import Counter

# Check original distribution
print("Before ADASYN:", Counter(y_train))

# Apply ADASYN to training data only
adasyn = ADASYN(random_state=42)
X_train_adasyn, y_train_adasyn = adasyn.fit_resample(X_train, y_train)

# Check new distribution
print("After ADASYN:", Counter(y_train_adasyn))

# Train XGBoost on ADASYN-resampled data
model_xgb_adasyn = XGBClassifier(random_state=42)
model_xgb_adasyn.fit(X_train_adasyn, y_train_adasyn)

# Predict on the original test set
y_pred_xgb_adasyn = model_xgb_adasyn.predict(X_test)

# Evaluate
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred_xgb_adasyn))
print("\nClassification Report:\n", classification_report(y_test, y_pred_xgb_adasyn))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb_adasyn))

Before ADASYN: Counter({0: 4133, 1: 1492})
After ADASYN: Counter({0: 4133, 1: 4080})
Accuracy: 0.7711442786069652

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.85      0.85      1030
           1       0.58      0.55      0.56       377

    accuracy                           0.77      1407
   macro avg       0.71      0.70      0.70      1407
weighted avg       0.77      0.77      0.77      1407


Confusion Matrix:
 [[879 151]
 [171 206]]

In [53]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Calculate scale_pos_weight (ratio of negative to positive class)
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print(f"scale_pos_weight: {scale_pos_weight:.2f}")

# Train XGBoost with scale_pos_weight
model_xgb_weighted = XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric='logloss'  # avoids warnings
)

model_xgb_weighted.fit(X_train, y_train)
y_pred_weighted = model_xgb_weighted.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_weighted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_weighted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_weighted))

scale_pos_weight: 2.77
Accuracy: 0.751954513148543

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.79      0.82      1030
           1       0.53      0.64      0.58       377

    accuracy                           0.75      1407
   macro avg       0.69      0.72      0.70      1407
weighted avg       0.77      0.75      0.76      1407


Confusion Matrix:
 [[817 213]
 [136 241]]

In [54]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Calculate the weight for the positive (minority) class
# Common approach: weight_positive = negative_count / positive_count
negative_count = (y_train == 0).sum()
positive_count = (y_train == 1).sum()
weight_positive = negative_count / positive_count if positive_count > 0 else 1
print(f"Negative class count: {negative_count}")
print(f"Positive class count: {positive_count}")
print(f"Weight for positive class: {weight_positive:.2f}")

# Create sample weights: higher weight for minority class
sample_weight = np.where(y_train == 1, weight_positive, 1.0)

# Train AdaBoost with sample weights
model_ada_weighted = AdaBoostClassifier(
    n_estimators=50,  # default, you can tune
    random_state=42
)

model_ada_weighted.fit(X_train, y_train, sample_weight=sample_weight)

# Predict and evaluate
y_pred_ada_weighted = model_ada_weighted.predict(X_test)

print("AdaBoost with sample weighting - Accuracy:", accuracy_score(y_test, y_pred_ada_weighted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_ada_weighted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_ada_weighted))

Negative class count: 4133
Positive class count: 1492
Weight for positive class: 2.77
AdaBoost with sample weighting - Accuracy: 0.7484008528784648

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.73      0.81      1030
           1       0.52      0.79      0.63       377

    accuracy                           0.75      1407
   macro avg       0.71      0.76      0.72      1407
weighted avg       0.80      0.75      0.76      1407


Confusion Matrix:
 [[756 274]
 [ 80 297]]

## **Hyper Parameter Optimization**

In [55]:
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier

param_grid = {
    'max_depth': [3, 4, 5, 6, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [100, 200, 300, 400],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.2],
    'scale_pos_weight': [1, scale_pos_weight]  # try both balanced and weighted
}

xgb = XGBClassifier(random_state=42, eval_metric='logloss')

# Use 'f1' or 'recall' scoring since churn is imbalanced
search = RandomizedSearchCV(
    xgb,
    param_grid,
    n_iter=50,
    cv=5,
    scoring='f1',  # or 'recall' if catching churn is priority
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

print("Best parameters:", search.best_params_)
print("Best CV F1 score:", search.best_score_)

# Use best model
best_model = search.best_estimator_
y_pred_best = best_model.predict(X_test)
print("\nTest Classification Report:\n", classification_report(y_test, y_pred_best))

Best parameters: {'subsample': 0.9, 'scale_pos_weight': np.float64(2.770107238605898), 'n_estimators': 100, 'min_child_weight': 3, 'max_depth': 3, 'learning_rate': 0.1, 'gamma': 0.2, 'colsample_bytree': 1.0}
Best CV F1 score: 0.6348121476648135

Test Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.74      0.81      1030
           1       0.52      0.79      0.63       377

    accuracy                           0.75      1407
   macro avg       0.71      0.76      0.72      1407
weighted avg       0.80      0.75      0.76      1407

In [56]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(best_model, 'best_xgboost_churn_model.pkl')

print("Best model successfully saved as 'best_xgboost_churn_model.pkl'")

Best model successfully saved as 'best_xgboost_churn_model.pkl'

## Trying out few more techniques

In [57]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(
    class_weight='balanced',
    random_state=42,
    n_estimators=300,
    max_depth=6
)
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.90      0.71      0.80      1030
           1       0.50      0.79      0.61       377

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.80      0.73      0.75      1407

In [60]:
from catboost import CatBoostClassifier

model_cat = CatBoostClassifier(
    auto_class_weights='Balanced',  # or 'SqrtBalanced'
    verbose=0,
    random_state=42
)
model_cat.fit(X_train, y_train)
y_pred_cat = model_cat.predict(X_test)
print(classification_report(y_test, y_pred_cat))

              precision    recall  f1-score   support

           0       0.89      0.77      0.82      1030
           1       0.53      0.73      0.62       377

    accuracy                           0.76      1407
   macro avg       0.71      0.75      0.72      1407
weighted avg       0.79      0.76      0.77      1407

In [63]:
from lightgbm import LGBMClassifier

model_lgb = LGBMClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42
)
model_lgb.fit(X_train, y_train)
y_pred_lgb = model_lgb.predict(X_test)
print(classification_report(y_test, y_pred_lgb))

[LightGBM] [Info] Number of positive: 1492, number of negative: 4133
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001067 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 606
[LightGBM] [Info] Number of data points in the train set: 5625, number of used features: 34
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.265244 -> initscore=-1.018886
[LightGBM] [Info] Start training from score -1.018886
              precision    recall  f1-score   support

           0       0.88      0.77      0.82      1030
           1       0.53      0.72      0.61       377

    accuracy                           0.75      1407
   macro avg       0.71      0.74      0.72      1407
weighted avg       0.79      0.75      0.76      1407

C:\Users\anupd\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

## **Optuna fine tuning**

In [65]:
import optuna
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, make_scorer

def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 1),  # L1 regularization
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 2), # L2 regularization
        'scale_pos_weight': trial.suggest_categorical('scale_pos_weight', [1, scale_pos_weight]),
        'random_state': 42,
        'eval_metric': 'logloss'
    }

    model = XGBClassifier(**params)

    # Use F1 for minority class as scorer
    f1_scorer = make_scorer(f1_score, average='binary', pos_label=1)
    score = cross_val_score(model, X_train, y_train, cv=5, scoring=f1_scorer, n_jobs=-1).mean()

    return score

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)  # Increase trials for better results

print("Best parameters:", study.best_params)
print("Best CV F1 score:", study.best_value)

# Train final model with best params
best_model_optuna = XGBClassifier(**study.best_params)
best_model_optuna.fit(X_train, y_train)
y_pred_optuna = best_model_optuna.predict(X_test)
print(classification_report(y_test, y_pred_optuna))

[I 2026-03-27 16:46:56,913] A new study created in memory with name: no-name-d1b524c4-bee1-443e-a134-5d9ced123937
[I 2026-03-27 16:47:01,394] Trial 0 finished with value: 0.6285089180869511 and parameters: {'max_depth': 3, 'learning_rate': 0.021544725869354762, 'n_estimators': 971, 'subsample': 0.8869265416935128, 'colsample_bytree': 0.6447361162013711, 'min_child_weight': 9, 'gamma': 0.31018404562587926, 'reg_alpha': 0.7777193471415694, 'reg_lambda': 0.43960284694058505, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 0 with value: 0.6285089180869511.
[I 2026-03-27 16:47:04,587] Trial 1 finished with value: 0.5803043567821334 and parameters: {'max_depth': 5, 'learning_rate': 0.07371619533339789, 'n_estimators': 598, 'subsample': 0.6878771297791642, 'colsample_bytree': 0.9125119443260208, 'min_child_weight': 9, 'gamma': 0.3306699410232945, 'reg_alpha': 0.22276176751155607, 'reg_lambda': 1.5457985088427315, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.6285089180869511.
[I 2026-03-27 16:47:07,830] Trial 2 finished with value: 0.5919185846071373 and parameters: {'max_depth': 8, 'learning_rate': 0.1358287986456117, 'n_estimators': 752, 'subsample': 0.8197124940356044, 'colsample_bytree': 0.8869125883908222, 'min_child_weight': 3, 'gamma': 0.46095494643629614, 'reg_alpha': 0.8394865788867786, 'reg_lambda': 0.7449168246983338, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 0 with value: 0.6285089180869511.
[I 2026-03-27 16:47:11,075] Trial 3 finished with value: 0.5840187121488688 and parameters: {'max_depth': 8, 'learning_rate': 0.04059082266863271, 'n_estimators': 223, 'subsample': 0.6870699683953754, 'colsample_bytree': 0.6310703053007085, 'min_child_weight': 7, 'gamma': 0.29875303558633604, 'reg_alpha': 0.8581835932628267, 'reg_lambda': 1.8538193315203728, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.6285089180869511.
[I 2026-03-27 16:47:12,817] Trial 4 finished with value: 0.5770525427010431 and parameters: {'max_depth': 8, 'learning_rate': 0.014647682204294403, 'n_estimators': 933, 'subsample': 0.8481767390856113, 'colsample_bytree': 0.8889775782385898, 'min_child_weight': 1, 'gamma': 0.13914544456767913, 'reg_alpha': 0.8559643930427464, 'reg_lambda': 1.6377391295717685, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.6285089180869511.
[I 2026-03-27 16:47:13,781] Trial 5 finished with value: 0.5701708160325971 and parameters: {'max_depth': 8, 'learning_rate': 0.2930673974662345, 'n_estimators': 864, 'subsample': 0.9149543591718778, 'colsample_bytree': 0.7332127393153658, 'min_child_weight': 8, 'gamma': 0.19515990490640478, 'reg_alpha': 0.30503465760037907, 'reg_lambda': 1.3327444389135412, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 0 with value: 0.6285089180869511.
[I 2026-03-27 16:47:14,365] Trial 6 finished with value: 0.5554719996361426 and parameters: {'max_depth': 10, 'learning_rate': 0.15963371221430542, 'n_estimators': 328, 'subsample': 0.6814980851865116, 'colsample_bytree': 0.9214727362786092, 'min_child_weight': 8, 'gamma': 0.2567861223488294, 'reg_alpha': 0.230655138058676, 'reg_lambda': 1.4024724776620723, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.6285089180869511.
[I 2026-03-27 16:47:15,068] Trial 7 finished with value: 0.5521683126187826 and parameters: {'max_depth': 8, 'learning_rate': 0.16480994025108306, 'n_estimators': 447, 'subsample': 0.6928401464791626, 'colsample_bytree': 0.9567260639390098, 'min_child_weight': 6, 'gamma': 0.4569936632193566, 'reg_alpha': 0.10400349990644386, 'reg_lambda': 1.6136633049164628, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.6285089180869511.
[I 2026-03-27 16:47:15,692] Trial 8 finished with value: 0.5784314985622242 and parameters: {'max_depth': 6, 'learning_rate': 0.09699371682956727, 'n_estimators': 463, 'subsample': 0.8022600608404814, 'colsample_bytree': 0.6238665795820382, 'min_child_weight': 3, 'gamma': 0.48137470215420014, 'reg_alpha': 0.84477799679559, 'reg_lambda': 1.9332080556065026, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.6285089180869511.
[I 2026-03-27 16:47:16,501] Trial 9 finished with value: 0.6254343264661761 and parameters: {'max_depth': 9, 'learning_rate': 0.02289280261220778, 'n_estimators': 443, 'subsample': 0.7630345623845907, 'colsample_bytree': 0.6611776448944854, 'min_child_weight': 10, 'gamma': 0.2586159376107462, 'reg_alpha': 0.580796361216857, 'reg_lambda': 1.4517897141542966, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 0 with value: 0.6285089180869511.
[I 2026-03-27 16:47:17,178] Trial 10 finished with value: 0.631292177910107 and parameters: {'max_depth': 3, 'learning_rate': 0.010754935996814385, 'n_estimators': 688, 'subsample': 0.9991143488231594, 'colsample_bytree': 0.7824783833195963, 'min_child_weight': 5, 'gamma': 0.024133542333295732, 'reg_alpha': 0.5926769957783609, 'reg_lambda': 0.010046982605525945, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 10 with value: 0.631292177910107.
[I 2026-03-27 16:47:18,042] Trial 11 finished with value: 0.6313773782857969 and parameters: {'max_depth': 3, 'learning_rate': 0.012790515441845039, 'n_estimators': 687, 'subsample': 0.9949854695367535, 'colsample_bytree': 0.7887487310000058, 'min_child_weight': 4, 'gamma': 0.0008358899382284457, 'reg_alpha': 0.6019200627364055, 'reg_lambda': 0.03735455509641497, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 11 with value: 0.6313773782857969.
[I 2026-03-27 16:47:18,680] Trial 12 finished with value: 0.6302979277682084 and parameters: {'max_depth': 3, 'learning_rate': 0.010160651181519658, 'n_estimators': 681, 'subsample': 0.999309132617164, 'colsample_bytree': 0.7980725233920867, 'min_child_weight': 4, 'gamma': 0.0015787508887033408, 'reg_alpha': 0.5620232543629011, 'reg_lambda': 0.09055086563074091, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 11 with value: 0.6313773782857969.
[I 2026-03-27 16:47:19,504] Trial 13 finished with value: 0.63126493479128 and parameters: {'max_depth': 4, 'learning_rate': 0.011025776138992445, 'n_estimators': 764, 'subsample': 0.9990786382137962, 'colsample_bytree': 0.8005919103448955, 'min_child_weight': 5, 'gamma': 0.004159186280215945, 'reg_alpha': 0.4372840969845245, 'reg_lambda': 0.07188358879244938, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 11 with value: 0.6313773782857969.
[I 2026-03-27 16:47:20,293] Trial 14 finished with value: 0.6221473390816906 and parameters: {'max_depth': 5, 'learning_rate': 0.037170111563238996, 'n_estimators': 647, 'subsample': 0.9283491240177272, 'colsample_bytree': 0.8022752637518685, 'min_child_weight': 1, 'gamma': 0.0879532490185857, 'reg_alpha': 0.6820366715416328, 'reg_lambda': 0.4604737788656462, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 11 with value: 0.6313773782857969.
[I 2026-03-27 16:47:21,094] Trial 15 finished with value: 0.6259348541565743 and parameters: {'max_depth': 4, 'learning_rate': 0.019644630951533845, 'n_estimators': 814, 'subsample': 0.9544784532154904, 'colsample_bytree': 0.7240555313769561, 'min_child_weight': 5, 'gamma': 0.07618711958451331, 'reg_alpha': 0.9884024094131715, 'reg_lambda': 0.32263347952412, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 11 with value: 0.6313773782857969.
[I 2026-03-27 16:47:21,845] Trial 16 finished with value: 0.6280285932627709 and parameters: {'max_depth': 3, 'learning_rate': 0.03861403139400208, 'n_estimators': 540, 'subsample': 0.9617405991766369, 'colsample_bytree': 0.8410310820548286, 'min_child_weight': 3, 'gamma': 0.06410441122627361, 'reg_alpha': 0.41721528926497986, 'reg_lambda': 0.9460191747891731, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 11 with value: 0.6313773782857969.
[I 2026-03-27 16:47:22,801] Trial 17 finished with value: 0.6257848255027689 and parameters: {'max_depth': 6, 'learning_rate': 0.015822970563122013, 'n_estimators': 675, 'subsample': 0.6013299027375574, 'colsample_bytree': 0.7303738695851039, 'min_child_weight': 6, 'gamma': 0.156742816503113, 'reg_alpha': 0.6405307915323729, 'reg_lambda': 0.7501820856652481, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 11 with value: 0.6313773782857969.
[I 2026-03-27 16:47:23,469] Trial 18 finished with value: 0.6294268292430802 and parameters: {'max_depth': 4, 'learning_rate': 0.0286020351624553, 'n_estimators': 553, 'subsample': 0.8739914485997033, 'colsample_bytree': 0.9993117601465211, 'min_child_weight': 4, 'gamma': 0.04744490123515593, 'reg_alpha': 0.4560039533415196, 'reg_lambda': 0.2552577961207776, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 11 with value: 0.6313773782857969.
[I 2026-03-27 16:47:24,046] Trial 19 finished with value: 0.6302491448472088 and parameters: {'max_depth': 5, 'learning_rate': 0.014712250611952773, 'n_estimators': 350, 'subsample': 0.7486150841796048, 'colsample_bytree': 0.6862721690582494, 'min_child_weight': 2, 'gamma': 0.12802803993226364, 'reg_alpha': 0.6992154146833379, 'reg_lambda': 0.0010180414924032856, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 11 with value: 0.6313773782857969.
[I 2026-03-27 16:47:24,939] Trial 20 finished with value: 0.628805944088383 and parameters: {'max_depth': 4, 'learning_rate': 0.010126371475316694, 'n_estimators': 855, 'subsample': 0.9479830903326035, 'colsample_bytree': 0.7663764134504712, 'min_child_weight': 4, 'gamma': 0.38106458490915074, 'reg_alpha': 0.35596276461509924, 'reg_lambda': 0.5723647230625389, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 11 with value: 0.6313773782857969.
[I 2026-03-27 16:47:25,655] Trial 21 finished with value: 0.6319256337621153 and parameters: {'max_depth': 3, 'learning_rate': 0.010017154787714321, 'n_estimators': 748, 'subsample': 0.9978713039635065, 'colsample_bytree': 0.8320728844378229, 'min_child_weight': 5, 'gamma': 0.007541125780118906, 'reg_alpha': 0.508388644178007, 'reg_lambda': 0.16744327631186937, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 21 with value: 0.6319256337621153.
[I 2026-03-27 16:47:26,380] Trial 22 finished with value: 0.6303101683866634 and parameters: {'max_depth': 3, 'learning_rate': 0.014126946318027751, 'n_estimators': 727, 'subsample': 0.9889510773754911, 'colsample_bytree': 0.845470183832463, 'min_child_weight': 5, 'gamma': 0.030912418200841955, 'reg_alpha': 0.5342907156974415, 'reg_lambda': 0.20619649643486418, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 21 with value: 0.6319256337621153.
[I 2026-03-27 16:47:27,040] Trial 23 finished with value: 0.6290134330007591 and parameters: {'max_depth': 3, 'learning_rate': 0.02659215431326757, 'n_estimators': 591, 'subsample': 0.910135795948638, 'colsample_bytree': 0.8412245933880957, 'min_child_weight': 6, 'gamma': 0.10396036799390679, 'reg_alpha': 0.623048819290656, 'reg_lambda': 0.21031255980375566, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 21 with value: 0.6319256337621153.
[I 2026-03-27 16:47:27,332] Trial 24 finished with value: 0.6304196664333419 and parameters: {'max_depth': 4, 'learning_rate': 0.01764851950557531, 'n_estimators': 102, 'subsample': 0.968673024517326, 'colsample_bytree': 0.7647283808546771, 'min_child_weight': 7, 'gamma': 0.03908229642079229, 'reg_alpha': 0.5087874378378903, 'reg_lambda': 0.617958574856514, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 21 with value: 0.6319256337621153.
[I 2026-03-27 16:47:28,270] Trial 25 finished with value: 0.6292336810212661 and parameters: {'max_depth': 5, 'learning_rate': 0.011862114857035323, 'n_estimators': 806, 'subsample': 0.8803762391342751, 'colsample_bytree': 0.7723724649771877, 'min_child_weight': 4, 'gamma': 0.19064279772013928, 'reg_alpha': 0.009425040694883702, 'reg_lambda': 1.1902806090893583, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 21 with value: 0.6319256337621153.
[I 2026-03-27 16:47:29,081] Trial 26 finished with value: 0.6184305089069586 and parameters: {'max_depth': 3, 'learning_rate': 0.05404876448374045, 'n_estimators': 910, 'subsample': 0.9313494413915966, 'colsample_bytree': 0.825251058581726, 'min_child_weight': 2, 'gamma': 0.005263060148965671, 'reg_alpha': 0.765720697281406, 'reg_lambda': 0.3341605715667152, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 21 with value: 0.6319256337621153.
[I 2026-03-27 16:47:30,111] Trial 27 finished with value: 0.6303638321186891 and parameters: {'max_depth': 7, 'learning_rate': 0.013159498497651622, 'n_estimators': 685, 'subsample': 0.976386312865018, 'colsample_bytree': 0.6867870259949235, 'min_child_weight': 5, 'gamma': 0.10616972776898433, 'reg_alpha': 0.3790664834681494, 'reg_lambda': 0.0137642252714897, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 21 with value: 0.6319256337621153.
[I 2026-03-27 16:47:30,729] Trial 28 finished with value: 0.6262241533923871 and parameters: {'max_depth': 4, 'learning_rate': 0.0276828215151169, 'n_estimators': 505, 'subsample': 0.8472644318261101, 'colsample_bytree': 0.8713808027567385, 'min_child_weight': 7, 'gamma': 0.1934422150005284, 'reg_alpha': 0.707445731271614, 'reg_lambda': 0.9515851816867212, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 21 with value: 0.6319256337621153.
[I 2026-03-27 16:47:31,523] Trial 29 finished with value: 0.632457670314065 and parameters: {'max_depth': 3, 'learning_rate': 0.02036465963767582, 'n_estimators': 640, 'subsample': 0.9024095068336933, 'colsample_bytree': 0.7443692428313711, 'min_child_weight': 3, 'gamma': 0.03941209209802275, 'reg_alpha': 0.4795076260139741, 'reg_lambda': 0.49145123119664236, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 29 with value: 0.632457670314065.
[I 2026-03-27 16:47:32,835] Trial 30 finished with value: 0.6215300233321812 and parameters: {'max_depth': 6, 'learning_rate': 0.020869141888952808, 'n_estimators': 983, 'subsample': 0.8876092545568005, 'colsample_bytree': 0.7451553325731101, 'min_child_weight': 2, 'gamma': 0.08087394598602621, 'reg_alpha': 0.49063480829350364, 'reg_lambda': 0.42624255593243543, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 29 with value: 0.632457670314065.
[I 2026-03-27 16:47:33,509] Trial 31 finished with value: 0.6320331955471568 and parameters: {'max_depth': 3, 'learning_rate': 0.017666905327106266, 'n_estimators': 639, 'subsample': 0.9441537682848602, 'colsample_bytree': 0.7066230054275587, 'min_child_weight': 3, 'gamma': 0.03703147806232231, 'reg_alpha': 0.6045573904792944, 'reg_lambda': 0.14444266638393566, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 29 with value: 0.632457670314065.
[I 2026-03-27 16:47:34,186] Trial 32 finished with value: 0.6316876138674822 and parameters: {'max_depth': 3, 'learning_rate': 0.017685494345277632, 'n_estimators': 612, 'subsample': 0.9444481563583564, 'colsample_bytree': 0.6777671718287827, 'min_child_weight': 3, 'gamma': 0.051524650012089876, 'reg_alpha': 0.48897348823142284, 'reg_lambda': 0.15885277440665665, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 29 with value: 0.632457670314065.
[I 2026-03-27 16:47:34,802] Trial 33 finished with value: 0.633600528658939 and parameters: {'max_depth': 4, 'learning_rate': 0.017769077122444903, 'n_estimators': 605, 'subsample': 0.9014021378443109, 'colsample_bytree': 0.69789694766044, 'min_child_weight': 3, 'gamma': 0.04742393297425172, 'reg_alpha': 0.3087124845929988, 'reg_lambda': 0.4694440234549683, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 33 with value: 0.633600528658939.
[I 2026-03-27 16:47:35,580] Trial 34 finished with value: 0.5840655544558517 and parameters: {'max_depth': 5, 'learning_rate': 0.031668133365157274, 'n_estimators': 625, 'subsample': 0.9105381942059321, 'colsample_bytree': 0.700901813887765, 'min_child_weight': 2, 'gamma': 0.15658271577041966, 'reg_alpha': 0.3125913300872217, 'reg_lambda': 0.7369890240200623, 'scale_pos_weight': 1}. Best is trial 33 with value: 0.633600528658939.
[I 2026-03-27 16:47:36,509] Trial 35 finished with value: 0.6215399912078209 and parameters: {'max_depth': 4, 'learning_rate': 0.04936547879498891, 'n_estimators': 740, 'subsample': 0.85086305888073, 'colsample_bytree': 0.6032595823752391, 'min_child_weight': 3, 'gamma': 0.11274590875920802, 'reg_alpha': 0.21909072631424403, 'reg_lambda': 0.44115706407942545, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 33 with value: 0.633600528658939.
[I 2026-03-27 16:47:37,165] Trial 36 finished with value: 0.628736865368449 and parameters: {'max_depth': 4, 'learning_rate': 0.02304994785450028, 'n_estimators': 569, 'subsample': 0.8925798403860464, 'colsample_bytree': 0.7081688725531942, 'min_child_weight': 1, 'gamma': 0.06107356461842674, 'reg_alpha': 0.275009038528776, 'reg_lambda': 0.5676652928369827, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 33 with value: 0.633600528658939.
[I 2026-03-27 16:47:37,724] Trial 37 finished with value: 0.5844293097834403 and parameters: {'max_depth': 3, 'learning_rate': 0.0687220356476931, 'n_estimators': 497, 'subsample': 0.8303826065954771, 'colsample_bytree': 0.7564301517559668, 'min_child_weight': 2, 'gamma': 0.3627080531088779, 'reg_alpha': 0.16983161929163737, 'reg_lambda': 0.32208656924169216, 'scale_pos_weight': 1}. Best is trial 33 with value: 0.633600528658939.
[I 2026-03-27 16:47:38,443] Trial 38 finished with value: 0.633791508104398 and parameters: {'max_depth': 3, 'learning_rate': 0.017492551083890587, 'n_estimators': 777, 'subsample': 0.9268702159034488, 'colsample_bytree': 0.6509657407654118, 'min_child_weight': 3, 'gamma': 0.03549209287755228, 'reg_alpha': 0.3729660562035534, 'reg_lambda': 0.6884814355209957, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 38 with value: 0.633791508104398.
[I 2026-03-27 16:47:39,139] Trial 39 finished with value: 0.587311446032978 and parameters: {'max_depth': 7, 'learning_rate': 0.016931137148877944, 'n_estimators': 408, 'subsample': 0.8581677735197853, 'colsample_bytree': 0.6326099758625167, 'min_child_weight': 3, 'gamma': 0.22425373457776568, 'reg_alpha': 0.39210699459153975, 'reg_lambda': 0.8080119088366926, 'scale_pos_weight': 1}. Best is trial 38 with value: 0.633791508104398.
[I 2026-03-27 16:47:39,983] Trial 40 finished with value: 0.6287084966534209 and parameters: {'max_depth': 4, 'learning_rate': 0.033309593830105226, 'n_estimators': 808, 'subsample': 0.9023276379914896, 'colsample_bytree': 0.6576515636555235, 'min_child_weight': 1, 'gamma': 0.15094222868153953, 'reg_alpha': 0.33437746067173163, 'reg_lambda': 1.1106486593441836, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 38 with value: 0.633791508104398.
[I 2026-03-27 16:47:40,735] Trial 41 finished with value: 0.6303718686942563 and parameters: {'max_depth': 3, 'learning_rate': 0.023831731291423325, 'n_estimators': 749, 'subsample': 0.9258399132618744, 'colsample_bytree': 0.7111482183995486, 'min_child_weight': 3, 'gamma': 0.035667405399416804, 'reg_alpha': 0.4501334063474389, 'reg_lambda': 0.6419283115215946, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 38 with value: 0.633791508104398.
[I 2026-03-27 16:47:41,620] Trial 42 finished with value: 0.6302053543000906 and parameters: {'max_depth': 3, 'learning_rate': 0.019797395338692143, 'n_estimators': 900, 'subsample': 0.9353450539106082, 'colsample_bytree': 0.6543069315834236, 'min_child_weight': 4, 'gamma': 0.027380712509606202, 'reg_alpha': 0.5234707536664677, 'reg_lambda': 0.47232268633209834, 'scale_pos_weight': np.float64(2.770107238605898)}. Best is trial 38 with value: 0.633791508104398.

Best parameters: {'max_depth': 3, 'learning_rate': 0.018492987501242012, 'n_estimators': 704, 'subsample': 0.9199239022888737, 'colsample_bytree': 0.632415738311747, 'min_child_weight': 10, 'gamma': 0.28560819110030206, 'reg_alpha': 0.1226552423780229, 'reg_lambda': 0.525059192222107, 'scale_pos_weight': np.float64(2.770107238605898)}
Best CV F1 score: 0.6356148839788464
              precision    recall  f1-score   support

           0       0.91      0.73      0.81      1030
           1       0.52      0.80      0.63       377

    accuracy                           0.75      1407
   macro avg       0.72      0.77      0.72      1407
weighted avg       0.81      0.75      0.76      1407

In [66]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(best_model_optuna, 'best_optuna_churn_model.pkl')

print("Best model successfully saved as 'best_optuna_churn_model.pkl'")

Best model successfully saved as 'best_optuna_churn_model.pkl'

In [67]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(model_ada_weighted, 'ada_boost_churn_model.pkl')

print("Best model successfully saved as 'ada_boost_churn_model.pkl'")

Best model successfully saved as 'ada_boost_churn_model.pkl'